### ISSUE TITLE
icp查询返回的json数据中已没有名为’serviceName‘的键

### ISSUE THREAD

**Issue by Yang-ST** [1in9e/icp-domains#2]
![图片](https://user-images.githubusercontent.com/62552619/158054311-271d85c2-921b-4465-9031-6726a0b7ea5f.png)
![图片](https://user-images.githubusercontent.com/62552619/158054381-7b4894ff-5442-4df5-8504-b925c7ae6695.png)
删除即可

**Comment by 1in9e** [comment]
已更新，感谢提醒
https://github.com/1in9e/icp-domains/tree/main
