### ISSUE TITLE
在linux中无法正常运行

### ISSUE THREAD

**Issue by liang-hiwin** [1in9e/icp-domains#3]
root@debian-106:~# python3 icp_domains.py qq.com
[*] qq.com 对应的备案号为粤B2-20090059-5

[*] 查询对象 粤B2-20090059 共有 1299 个备案域名
[+] 域名具体信息如下：
Traceback (most recent call last):
  File "/root/icp_domains.py", line 235, in <module>
    main(sys.argv[1])
  File "/root/icp_domains.py", line 193, in main
    domain_site_name = info_base['serviceName']
KeyError: 'serviceName'

**Comment by 1in9e** [comment]
源站字段改变缘故，已更新，感谢提醒
https://github.com/1in9e/icp-domains/tree/main
