### ISSUE TITLE
备案查询功能是否可以集成到我的项目domain-admin

### ISSUE THREAD

**Issue by mouday** [1in9e/icp-domains#5]
基于Python3 + Vue3.js 技术栈实现的域名和SSL证书监测平台
https://github.com/mouday/domain-admin

![image](https://github.com/1in9e/icp-domains/assets/24365682/c2cd570a-12e5-47d5-a58f-717f3672191c)

**Comment by 1in9e** [comment]
可以的哈，open share~

**Comment by mouday** [comment]
我采用了项目中api方式，感谢分享查询方式，同时也邀请你体验我们的项目
